src/UserBundle/Entity/User.php
<?php

namespace UserBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="UserBundle\Repository\UserRepository")
 * @ORM\Table(name="users")
 * @UniqueEntity(fields={"email"}, message="It looks like you already have an account!")
 */
class User implements UserInterface
{
    const ROLE_DEFAULT = 'ROLE_USER';
    const ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN';

    /**
     * @ORM\Id
     * @ORM\Column(type="integer", options={"unsigned":true})
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $active = false;

    /**
     * @var \DateTime $created
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    protected $created;

    /**
     * @var \DateTime $updated
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    protected $updated;

    /**
     * @Assert\NotBlank()
     * @Assert\Email()
     * @ORM\Column(type="string", unique=true)
     */
    protected $email;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $name;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $password = '';

    /**
     * @Assert\NotBlank(groups="Registration")
     * @Assert\Length(
     *      min = 6,
     *      minMessage = "Your password must be at least {{ limit }} characters long",
     * )
     */
    protected $plainPassword;

    /**
     * @ORM\Column(type="json_array")
     */
    protected $roles = [];

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $recoverToken;

    /**
     * @var \DateTime $created
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $recoverExpires;

    public function __construct()
    {
        $this->orgs = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getActive()
    {
        return $this->active;
    }

    public function setActive($active)
    {
        $this->active = $active;
    }

    public function getCreated()
    {
        return $this->created;
    }

    public function setCreated($created)
    {
        $this->created = $created;
    }

    public function getUpdated()
    {
        return $this->updated;
    }

    public function setUpdated($updated)
    {
        $this->updated = $updated;
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function getRoles()
    {
        $roles = $this->roles;
        if (!in_array(User::ROLE_DEFAULT, $roles)) {
            $roles[] = User::ROLE_DEFAULT;
        }
        return $roles;
    }

    public function setRoles($roles)
    {
        $this->roles = $roles;
    }

    public function hasRole($role)
    {
        return in_array(strtoupper($role), $this->getRoles(), true);
    }

    public function getPassword()
    {
        return $this->password;
    }

    public function setPassword($password)
    {
        $this->password = $password;
    }

    public function getSalt()
    {
    }

    public function eraseCredentials()
    {
        $this->plainPassword = null;
    }

    public function getEmail()
    {
        return $this->email;
    }

    public function setEmail($email)
    {
        $this->email = $email;
    }

    public function getName()
    {
        return $this->name;
    }

    public function setName($name)
    {
        $this->name = $name;
    }


    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    public function setPlainPassword($plainPassword)
    {
        $this->plainPassword = $plainPassword;
        // guarantees that the entity looks "dirty" to Doctrine
        // when changing the plainPassword
        // $this->password = null;
    }

    public function getRecoverToken()
    {
        return $this->recoverToken;
    }

    public function setRecoverToken($recoverToken)
    {
        $this->recoverToken = $recoverToken;
    }

    public function getRecoverExpires()
    {
        return $this->recoverExpires;
    }

    public function setRecoverExpires($recoverExpires)
    {
        $this->recoverExpires = $recoverExpires;
    }

    public function setSuperAdmin($boolean)
    {
        if (true === $boolean) {
            $this->addRole(static::ROLE_SUPER_ADMIN);
        } else {
            $this->removeRole(static::ROLE_SUPER_ADMIN);
        }

        return $this;
    }

    public function addRole($role)
    {
        $role = strtoupper($role);
        if ($role === static::ROLE_DEFAULT) {
            return $this;
        }

        if (!in_array($role, $this->roles, true)) {
            $this->roles[] = $role;
        }

        return $this;
    }

    public function removeRole($role)
    {
        if (false !== $key = array_search(strtoupper($role), $this->roles, true)) {
            unset($this->roles[$key]);
            $this->roles = array_values($this->roles);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->name.' '.$this->email;
    }

    public function getDisplayName()
    {
        if (!empty($this->name)) {
            return $this->name;
        }
        return $this->email;
    }
}

src/UserBundle/Resources/views/admin/_form.html.twig
    {{ form_start(userForm) }}
    <div class="md-form">
        {{ form_row(userForm.email) }}
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="md-form">
                {{ form_row(userForm.name) }}
            </div>
        </div>
    </div>

    {{ form_row(userForm.roles, { 'attr': {'class': 'mdb-select'} }) }}

    <div class="row">
        <div class="col-sm-12 text-right">
            <div class="btn-group" role="group" aria-label="Actions">
                <a href="{{ path('admin_user_list') }}" class="btn btn-secondary">Cancel</a>
                <button type="submit" class="btn btn-primary pull-right" formnovalidate>Save</button>
            </div>
        </div>
    </div>

    {{ form_end(userForm) }}

src/UserBundle/Resources/views/admin/delete.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ form_start(form) }}
    <div class="container">
        <div class="card card-block">
            <div class="row">
                <div class="col-md-12">
                    <h3>Delete User</h3>
                        <p class="text-md-center">Are you sure you would like to delete this user?</p>
                        <h3 class="text-md-center">{{ user.email }}</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 text-right">
                    <div class="btn-group" role="group" aria-label="Actions">
                        <a href="{{ path('admin_user_list') }}" class="btn btn-secondary">Cancel</a>
                        <button type="submit" class="btn btn-danger" formnovalidate>Delete</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{ form_end(form) }}
{% endblock %}

src/UserBundle/Resources/views/admin/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
    <div class="card card-block">
        <h1>Edit User</h1>
        <div class="row">
            <div class="col-md-12">
                {{ include('UserBundle:admin:_form.html.twig') }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/UserBundle/Resources/views/admin/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="card card-block">
            <div class="row">
                <div class="col-sm-12">
                    <div class="action-buttons">
                        <a href="{{ path('admin_user_new') }}" class="btn btn-sm btn-secondary"><i class="fa fa-plus" aria-hidden="true"></i> New User</a>
                    </div>

                    <h1>Users</h1>
                    <div class="record-count pull-right">
                        <small>Records: {{ pagination.getTotalItemCount|number_format }}</small>
                    </div>
                    <table class="table table-sm table-striped">
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Roles</th>
                            <th>{{ knp_pagination_sortable(pagination, 'Created', 'u.created') }}</th>
                            <th class="ops">&nbsp;</th>
                        </tr>
                        {% for user in pagination %}
                            <tr>
                                <td><a href="#">{{ user.displayName }}</a></td>
                                <td><a href="#">{{ user.email }}</a></td>
                                <td>
                                {% for role in user.roles %}
                                    {% if role != 'ROLE_USER' %}
                                    <div><small>{{ role }}</small></div>
                                    {% endif %}
                                {% endfor %}
                                </td>
                                <td>{{ user.created|date('m/d/Y h:ia') }}</td>
                                <td>
                                    <a href="{{ path('admin_user_edit', {'id': user.id}) }}"><i class="fa fa-edit" aria-hidden="true"></i> edit</a> &nbsp;
                                    <a href="{{ path('admin_user_delete', {'id': user.id}) }}"><i class="fa fa-remove" aria-hidden="true"></i> delete</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                    <div class="navigation text-center">
                        {{ knp_pagination_render(pagination) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/UserBundle/Resources/views/admin/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="card card-block">
            <h1>Edit User</h1>
            <div class="row">
                <div class="col-md-12">
                    {{ include('UserBundle:admin:_form.html.twig') }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}